#!/usr/bin/ruby
# coding: utf-8
#
# パソコンファイルのサムネをGyazoにアップしつつ本体をクラウドにバックアップする
#
#  * 画像の場合は縮小画像をGyazoにアップ
#  * Wordファイルなどの場合はサムネをGyazoにアップ
#   - qlmanageというMacのコマンドを使う
#

if ARGV.length == 0
  STDERR.puts "Upload files to Gyazo"
  STDERR.puts "Usage: % upgyazo CIMG0123.img"
  STDERR.puts "       % upgyazo myfile.doc"
  exit
end

#
# Gyazo.comの認証のためにGYAZO_TOKEN環境変数を利用
# たとえば~/.profile にこう書いておく
#   export GYAZO_TOKEN=0123456789...
#
GYAZO_TOKEN=ENV['GYAZO_TOKEN']
unless GYAZO_TOKEN
  STDERR.puts "Set the environment variable 'GYAZO_TOKEN'."
  STDERR.puts "You can get the access token at https://gyazo.com/oauth/applications"
  exit
end

#
# Gyazo APIを呼ぶ本体ライブラリ/ファイルをクラウドにセーブするライブラリ
#

prog = $0
prog = File.readlink(prog) if File.symlink?(prog)
progdir = File.dirname(prog)

require "#{progdir}/upgyazo"
require "#{progdir}/cloud"

gu = GyazoUpload.new GYAZO_TOKEN

ARGV.each { |arg|
  unless File.exist?(arg)
    STDERR.puts "File/dir <#{arg}> not found"
    next
  end
  if File.directory?(arg) then
    Find.find(arg).each { |file|
      gu.process file if File.file?(file)
    }
  else
    gu.process arg
  end
}
