#!/usr/bin/ruby
# coding: utf-8
#
# % upgyazo CIMG0123.img
#
# 画像の場合はサムネをアップ
# 文書ファイルなどの場合はアイコンをアップ
#

if ARGV.length == 0
  STDERR.puts "Upload files to Gyazo"
  STDERR.puts "Usage: % upgyazo filename"
  exit
end

prog = $0
prog = File.readlink(prog) if File.symlink?(prog)
dir = File.dirname(prog)

require "#{dir}/upgyazo"

# Gyazo.comの認証のために ~/.profile にこういうのを書いておく
# export GYAZO_TOKEN=0123456789...

GYAZO_TOKEN=ENV['GYAZO_TOKEN']
exit if GYAZO_TOKEN.nil?
upload = GyazoUpload.new GYAZO_TOKEN

ARGV.each { |arg|
  next unless File.exist?(arg)
  if File.directory?(arg) then
    Find.find(arg).each { |file|
      upload.process file if File.file?(file)
    }
  else
    upload.process arg
  end
}

